### PR TITLE
Lambda function to scale ASG based on Github webhooks

### PR DESCRIPTION
**Pull request by ashb**
This is very-rough and ready right now (it has no tests, nor instructions for deployin/updating it/how it works) - I'll add those when I have time over the next few days/week

It uses https://aws.github.io/chalice/

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
I see how the lambda works, but I woiuld love to know who is hitting the endpoint ? Is the blog I've sent some time ago describing the architecture? I do not need fully fledged description just few words on how it work. We can capture it later of course in a more peristent way.

**Comment by ashb** [comment]
https://040code.github.io/2020/05/25/scaling-selfhosted-action-runners - it roughly follows that, but we had to make some changes due to ASF github permissions (we can't have admin tokens that can create/destroy runners)

Very roughly:

This Lambda is behind an AWS API Gateway.

There is a GitHub app (had to be created in my personal account) configured to get "check" callbacks sent to the API Gateway.

The GitHub app is installed in the `apache/airflow` (and currently also `apache/airflow-site`) repos

(The scale in is handled by a custom metric sent to CloudWatch.)

PR for automation of the other parts is coming - I'm focusing on getting it working mostly, automation of all the AWS and set up of CI workflows for this repo to follow in the future.

**Comment by ashb** [comment]
I'm not sure the logic about when to create a new instance works.

**Comment by ashb** [comment]
I have been deploying this with `chalice deploy --profile airflow --stage prod`

**Comment by ashb** [comment]
This still needs way more tests, but that can be worked on over time.

**Pull request merged**
